---
version: "3.4"
services:
  keycloak:
    build:
      context: ..
      target: e2e_test
    volumes:
      - ./fixtures:/opt/jboss/keycloak/data/import:ro
      - ./standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml:ro
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/data/import/kc-test-realm.json
      - DB_VENDOR=h2
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/auth/realms/test-realm"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
