---
version: "3.4"
services:
  keycloak:
    build:
      context: ..
      target: e2e_test
    command: start-dev --import-realm
    volumes:
      - ./fixtures:/opt/keycloak/data/import:ro
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_DB=dev-mem
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/realms/test-realm"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
