openapi: "3.0.2"
info:
  title: Keycloak Realm Webhook API
  version: "20.0.3.1"
paths:
  /realms/{realmId}/pckhoi-webhook/webhooks:
    parameters:
      - name: realmId
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: createWebhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/webhook"
      responses:
        "201":
          description: Created
    get:
      operationId: listWebhooks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/webhook"
    delete:
      operationId: deleteAllWebhooks
      responses:
        "200":
          description: OK
  /realms/{realmId}/pckhoi-webhook/webhooks/{webhookId}:
    parameters:
      - name: realmId
        in: path
        required: true
        schema:
          type: string
      - name: webhookId
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getWebhook
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/webhook"
    delete:
      operationId: deleteWebhook
      responses:
        "200":
          description: OK
components:
  schemas:
    webhook:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        url:
          type: string
          format: url
        filters:
          type: array
          items:
            $ref: "#/components/schemas/eventFilter"
    eventFilter:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userEventType:
          type: string
          enum:
            - AUTHREQID_TO_TOKEN
            - AUTHREQID_TO_TOKEN_ERROR
            - CLIENT_DELETE
            - CLIENT_DELETE_ERROR
            - CLIENT_INFO
            - CLIENT_INFO_ERROR
            - CLIENT_INITIATED_ACCOUNT_LINKING
            - CLIENT_INITIATED_ACCOUNT_LINKING_ERROR
            - CLIENT_LOGIN
            - CLIENT_LOGIN_ERROR
            - CLIENT_REGISTER
            - CLIENT_REGISTER_ERROR
            - CLIENT_UPDATE
            - CLIENT_UPDATE_ERROR
            - CODE_TO_TOKEN
            - CODE_TO_TOKEN_ERROR
            - CUSTOM_REQUIRED_ACTION
            - CUSTOM_REQUIRED_ACTION_ERROR
            - DELETE_ACCOUNT
            - DELETE_ACCOUNT_ERROR
            - EXECUTE_ACTION_TOKEN
            - EXECUTE_ACTION_TOKEN_ERROR
            - EXECUTE_ACTIONS
            - EXECUTE_ACTIONS_ERROR
            - FEDERATED_IDENTITY_LINK
            - FEDERATED_IDENTITY_LINK_ERROR
            - GRANT_CONSENT
            - GRANT_CONSENT_ERROR
            - IDENTITY_PROVIDER_FIRST_LOGIN
            - IDENTITY_PROVIDER_FIRST_LOGIN_ERROR
            - IDENTITY_PROVIDER_LINK_ACCOUNT
            - IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR
            - IDENTITY_PROVIDER_LOGIN
            - IDENTITY_PROVIDER_LOGIN_ERROR
            - IDENTITY_PROVIDER_POST_LOGIN
            - IDENTITY_PROVIDER_POST_LOGIN_ERROR
            - IDENTITY_PROVIDER_RESPONSE
            - IDENTITY_PROVIDER_RESPONSE_ERROR
            - IDENTITY_PROVIDER_RETRIEVE_TOKEN
            - IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR
            - IMPERSONATE
            - IMPERSONATE_ERROR
            - INTROSPECT_TOKEN
            - INTROSPECT_TOKEN_ERROR
            - INVALID_SIGNATURE
            - INVALID_SIGNATURE_ERROR
            - LOGIN
            - LOGIN_ERROR
            - LOGOUT
            - LOGOUT_ERROR
            - OAUTH2_DEVICE_AUTH
            - OAUTH2_DEVICE_AUTH_ERROR
            - OAUTH2_DEVICE_CODE_TO_TOKEN
            - OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR
            - OAUTH2_DEVICE_VERIFY_USER_CODE
            - OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR
            - PERMISSION_TOKEN
            - PERMISSION_TOKEN_ERROR
            - PUSHED_AUTHORIZATION_REQUEST
            - PUSHED_AUTHORIZATION_REQUEST_ERROR
            - REFRESH_TOKEN
            - REFRESH_TOKEN_ERROR
            - REGISTER
            - REGISTER_ERROR
            - REGISTER_NODE
            - REGISTER_NODE_ERROR
            - REMOVE_FEDERATED_IDENTITY
            - REMOVE_FEDERATED_IDENTITY_ERROR
            - REMOVE_TOTP
            - REMOVE_TOTP_ERROR
            - RESET_PASSWORD
            - RESET_PASSWORD_ERROR
            - RESTART_AUTHENTICATION
            - RESTART_AUTHENTICATION_ERROR
            - REVOKE_GRANT
            - REVOKE_GRANT_ERROR
            - SEND_IDENTITY_PROVIDER_LINK
            - SEND_IDENTITY_PROVIDER_LINK_ERROR
            - SEND_RESET_PASSWORD
            - SEND_RESET_PASSWORD_ERROR
            - SEND_VERIFY_EMAIL
            - SEND_VERIFY_EMAIL_ERROR
            - TOKEN_EXCHANGE
            - TOKEN_EXCHANGE_ERROR
            - UNREGISTER_NODE
            - UNREGISTER_NODE_ERROR
            - UPDATE_CONSENT
            - UPDATE_CONSENT_ERROR
            - UPDATE_EMAIL
            - UPDATE_EMAIL_ERROR
            - UPDATE_PASSWORD
            - UPDATE_PASSWORD_ERROR
            - UPDATE_PROFILE
            - UPDATE_PROFILE_ERROR
            - UPDATE_TOTP
            - UPDATE_TOTP_ERROR
            - USER_INFO_REQUEST
            - USER_INFO_REQUEST_ERROR
            - VERIFY_EMAIL
            - VERIFY_EMAIL_ERROR
            - VERIFY_PROFILE
            - VERIFY_PROFILE_ERROR
        adminEventResourceType:
          type: string
          enum:
            - AUTH_EXECUTION
            - AUTH_EXECUTION_FLOW
            - AUTH_FLOW
            - AUTHENTICATOR_CONFIG
            - AUTHORIZATION_POLICY
            - AUTHORIZATION_RESOURCE
            - AUTHORIZATION_RESOURCE_SERVER
            - AUTHORIZATION_SCOPE
            - CLIENT
            - CLIENT_INITIAL_ACCESS_MODEL
            - CLIENT_ROLE
            - CLIENT_ROLE_MAPPING
            - CLIENT_SCOPE
            - CLIENT_SCOPE_CLIENT_MAPPING
            - CLIENT_SCOPE_MAPPING
            - CLUSTER_NODE
            - COMPONENT
            - CUSTOM
            - GROUP
            - GROUP_MEMBERSHIP
            - IDENTITY_PROVIDER
            - IDENTITY_PROVIDER_MAPPER
            - PROTOCOL_MAPPER
            - REALM
            - REALM_ROLE
            - REALM_ROLE_MAPPING
            - REALM_SCOPE_MAPPING
            - REQUIRED_ACTION
            - USER
            - USER_FEDERATION_MAPPER
            - USER_FEDERATION_PROVIDER
            - USER_LOGIN_FAILURE
            - USER_SESSION
        adminEventOperationType:
          type: string
          enum:
            - ACTION
            - CREATE
            - DELETE
            - UPDATE
