---
name: "tagged-release"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "maven-bot"
          git-release-bot-email: "maven-bot@pckhoi.org"

          maven-args:
            "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip
            -DdockerCompose.skip -Dmaven.deploy.skip=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
