---
name: "tagged-release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Release
        uses: qcastel/github-actions-maven-release@v1.12.34
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
        with:
          git-release-bot-name: "maven-bot"
          git-release-bot-email: "maven-bot@pckhoi.org"
          release-branch-name: main
          maven-args:
            "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip
            -DdockerCompose.skip -Dmaven.deploy.skip=true -DbranchName=kc-19.0.1"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
